#!/usr/bin/env python3
"""
Real-Time SCADA Attack Demonstration
Shows how the attack UI manipulates actual DNP3 data
"""

import sys
import os
import time
from pathlib import Path

# Add simulation directory to path
simulation_dir = Path(__file__).parent / "simulation"
sys.path.append(str(simulation_dir))

from ieee39_system_strict import StrictIEEE39BusSystem
from integrated_scada import SCADAMaster
from integrated_rtu import IntegratedRTU, RTUConfig
from mock_dnp3 import MockDNP3Channel

def demonstrate_real_attack():
    """Demonstrate how the attack UI actually manipulates SCADA data"""
    
    print("🕷️ REAL-TIME SCADA ATTACK DEMONSTRATION")
    print("=" * 60)
    print("This shows how the Streamlit UI manipulates actual RTU data")
    print()
    
    # Step 1: Initialize the real system
    print("1️⃣ Initializing IEEE 39-Bus System...")
    power_system = StrictIEEE39BusSystem()
    power_system.run_pypower_powerflow()  # Run power flow analysis
    print("✅ Power system operational")
    
    # Step 2: Create DNP3 channel
    print("\n2️⃣ Creating Mock DNP3 Channel...")
    dnp3_channel = MockDNP3Channel()
    print("✅ DNP3 communication channel established")
    
    # Step 3: Create SCADA master
    print("\n3️⃣ Initializing SCADA Master...")
    scada = SCADAMaster(dnp3_channel, power_system)
    print("✅ SCADA master ready")
    
    # Step 4: Create a few RTUs for demonstration
    print("\n4️⃣ Creating RTU Outstations...")
    rtus = []
    for i, bus in enumerate([30, 31, 32], 1):
        config = RTUConfig(
            rtu_id=i,
            bus_number=bus,
            station_name=f"Demo_RTU_{i}"
        )
        rtu = IntegratedRTU(config, power_system, dnp3_channel)
        rtus.append(rtu)
        print(f"  ✅ RTU {i} created for Bus {bus}")
    
    # Step 5: Start the system
    print("\n5️⃣ Starting SCADA-RTU System...")
    scada.start_polling()
    time.sleep(3)  # Let system stabilize
    print("✅ System operational and polling")
    
    # Step 6: Show normal measurements
    print("\n6️⃣ Normal System Measurements:")
    measurements = scada.get_recent_measurements(limit=9)
    for i, measurement in enumerate(measurements):
        if i < 6:  # Show first 6 measurements
            print(f"  RTU {measurement['rtu_id']}: {measurement['point_type']} = {measurement['value']:.4f} {measurement.get('unit', '')}")
    
    # Step 7: Activate attack interceptor
    print("\n7️⃣ ACTIVATING ATTACK INTERCEPTOR...")
    dnp3_channel.activate_attack_interceptor()
    print("🔴 Attack interceptor ACTIVE - ready to manipulate data")
    
    # Step 8: Set attack manipulations (like the UI does)
    print("\n8️⃣ Setting Attack Manipulations...")
    print("  🎯 RTU 1: +0.15 pu voltage offset")
    dnp3_channel.set_attack_manipulation(rtu_id=1, voltage_offset=0.15)
    
    print("  🎯 RTU 2: -0.10 pu voltage offset")
    dnp3_channel.set_attack_manipulation(rtu_id=2, voltage_offset=-0.10)
    
    print("  🎯 RTU 3: +1.5 Hz frequency offset")
    dnp3_channel.set_attack_manipulation(rtu_id=3, frequency_offset=1.5)
    
    # Step 9: Wait for manipulated data
    print("\n9️⃣ Waiting for manipulated measurements...")
    time.sleep(5)  # Wait for several polling cycles
    
    # Step 10: Show manipulated measurements
    print("\n🔟 MANIPULATED System Measurements:")
    measurements = scada.get_recent_measurements(limit=9)
    manipulated_count = 0
    for measurement in measurements:
        if measurement['rtu_id'] <= 3:  # Only show manipulated RTUs
            quality_indicator = ""
            # Check if this measurement was manipulated
            if ('voltage_magnitude' in measurement['point_type'] and 
                measurement['rtu_id'] in [1, 2]):
                quality_indicator = " 🔴 MANIPULATED"
                manipulated_count += 1
            elif ('frequency' in measurement['point_type'] and 
                  measurement['rtu_id'] == 3):
                quality_indicator = " 🔴 MANIPULATED"
                manipulated_count += 1
            
            print(f"  RTU {measurement['rtu_id']}: {measurement['point_type']} = {measurement['value']:.4f} {measurement.get('unit', '')}{quality_indicator}")
    
    if manipulated_count > 0:
        print(f"\n✅ SUCCESS: {manipulated_count} measurements successfully manipulated!")
        print("🕷️ This is exactly what the Streamlit UI does in real-time")
    else:
        print("\n⏳ No manipulated data detected yet - attack may need more time")
    
    # Step 11: Show alarms generated by manipulated data
    print("\n1️⃣1️⃣ Checking for Generated Alarms...")
    alarms = scada.get_recent_alarms(limit=5)
    if alarms:
        print("🚨 ALARMS TRIGGERED BY MANIPULATED DATA:")
        for alarm in alarms:
            print(f"  ⚠️  RTU {alarm['rtu_id']}: {alarm['message']}")
    else:
        print("  No alarms generated (normal for small offsets)")
    
    # Cleanup
    print("\n1️⃣2️⃣ Cleaning up...")
    dnp3_channel.deactivate_attack_interceptor()
    scada.stop_polling()
    for rtu in rtus:
        rtu.stop()
    print("✅ System stopped")
    
    print("\n" + "=" * 60)
    print("🎯 DEMONSTRATION COMPLETE!")
    print()
    print("KEY POINTS:")
    print("• The Streamlit UI connects to THIS EXACT SAME SYSTEM")
    print("• Attack manipulations are applied through DNP3 interception")
    print("• RTU measurements are actually modified in real-time")
    print("• SCADA receives the manipulated data as if it were real")
    print("• This creates realistic cybersecurity attack scenarios")
    print()
    print("🌐 Try the real-time UI at: http://localhost:8502")
    print("   (Run: streamlit run mitm/real_attack_ui.py --server.port 8502)")

if __name__ == "__main__":
    demonstrate_real_attack()